version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_USER=mysqladmin
      - MYSQL_PASSWORD=mysqladmin
      - MYSQL_ROOT_PASSWORD=mysqladmin
      - MYSQL_DATABASE=csharpapp_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local